import type { RecordItem } from "./recordUtils";

export const mockRecords: RecordItem[] = [
  {
    recordId: 612,
    programId: 303,
    centerId: 1,
    startTime: "2025-08-13T11:22:33",
    endTime: "2025-08-13T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout_kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: false,
  },
  {
    recordId: 611,
    programId: 303,
    centerId: 1,
    startTime: "2025-08-12T11:22:33",
    endTime: "2025-08-12T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout_kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: false,
  },
  {
    recordId: 610,
    programId: 302,
    centerId: 1,
    startTime: "2025-08-11T11:22:33",
    endTime: "2025-08-11T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout_kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: true,
  },
  {
    recordId: 609,
    programId: 302,
    centerId: 1,
    startTime: "2025-08-10T11:22:33",
    endTime: "2025-08-11T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout_kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: true,
  },
  {
    recordId: 608,
    programId: 301,
    centerId: 1,
    startTime: "2025-08-09T11:22:33",
    endTime: "2025-08-09T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout_kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: true,
  },
  {
    recordId: 607,
    programId: 301,
    centerId: 1,
    startTime: "2025-08-08T11:22:33",
    endTime: "2025-08-08T12:22:33",
    participantCount: 2,
    routineKind: "workout_programs_selections_byPersonal",
    cognitiveKind: "workout.kinds_cognitive_kinds_dualtasking",
    singingKind: "workout_kinds_singing",
    durationKind: "workout_duration_60minutes",
    surveysExist: true,
  },
];
